# Generated by Django 5.0.3 on 2024-04-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_teacher_facebook_teacher_linkedin_teacher_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
