# Generated by Django 5.0.3 on 2024-04-17 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='speciality',
            field=models.ManyToManyField(to='course.speciality'),
        ),
    ]
