# Generated by Django 5.0.3 on 2024-04-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
